### ISSUE TITLE
Seeking Assistance: Location of 'pdf_only_epoch0-iter9999' Checkpoint in Repository

### ISSUE THREAD

**Issue by leandrohattori** [OpenGVLab/ChartAst#10]
Hello everyone,

I hope this message finds you well. I am currently looking for the 'pdf_only_epoch0-iter9999' checkpoint in the repository. Could someone kindly guide me to its location or provide information on where I can find it?

Thank you in advance for your assistance.

Best regards,

Leandro Takeshi Hattori.

**Comment by FanqingM** [comment]
Hi,
We do not provide this checkpoint because this is not used.
For inference you should run sh accessory/exps/finetune/mm/test.sh # run accessory/single_turn_eval.py
and you should use checkpoint below:
The ChartAssistant, which has undergone two-stage training on ChartSFT, has been open-sourced. You can download it through the following link.

https://pan.baidu.com/s/1t0QPLDfULNovnYKtsQxjOQ password: 10el
[HuggingFace](https://huggingface.co/FanqingM/ChartAssistant) : put consolidated.00-of-02.model.pth and consolidated.01-of-02.model.pth in one directory, and replace pretrained_path in the scipt as it.

For training, we use pretrained checkpoint as SPHINX-v1, which is in SPHINX repo.

If there any problems? please tell me.

**Comment by FanqingM** [comment]
http://106.14.127.192:7861/
Hi you can use this online demo.
