### ISSUE TITLE
How did you get instructions for some parts of ChartSFT

### ISSUE THREAD

**Issue by tannq-jo** [OpenGVLab/ChartAst#14]
Hi,
Congratulations on your great work! I am curious about how you created the instructions for Chart Summarization since the datasets made of this task (e.g. Chart-to-Text, ChartSumm) do not originally come with the instructions. Also, in the pre-trained stage with Chart-to-Table Translation, did you set one fixed instruction for all samples or apply the same strategies to generate instructions as Chart Summarization?

Thank you for your attention to this matter.

**Comment by FanqingM** [comment]
In ChartAst-D, we introduced special tokens for these tasks to guide the model in performing them. For ChartAst-S, since we did not fine-tune all parts of the LLM, it is inherently prepared to understand different representations of the same sentence, such as "Describe this chart" and "Give a summary of this chart," which have similar effects.

**Comment by tannq-jo** [comment]
Thank you for your thoughtful reply. The explanation ChartAst-S is such a mind-blowing thing to me, it gives me an out-of-the-box thinking :) This is really helpful for me.
