### ISSUE TITLE
If I want to fine tune on Chinese data, how much data volume and GPU resources do I need?

### ISSUE THREAD

**Issue by Sunting78** [OpenGVLab/ChartAst#20]
thanks

**Comment by FanqingM** [comment]
I think you can do some fine tuning based on ChartAst-S. The simplest way is:
1. Generate Chinese chart-table pairs by yourself and perform stage-1 training
2. Refer to the QA generation process in the article to generate QA data for the data in step 1 and perform training.

It is difficult to say the specific requirements, because the process in step 1 can actually generate a lot of samples, so I suggest you start with 50,000 pairs. This process takes about half a day on an 8-card A100

**Comment by Sunting78** [comment]
Thanks a lot for your reply.
